// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MockAPI.Data;

#nullable disable

namespace MockAPI.Migrations
{
    [DbContext(typeof(MockApiDbContext))]
    partial class MockApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MockAPI.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "United Kingdom",
                            ShortName = "UK"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wales",
                            ShortName = "WAL"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Scotland",
                            ShortName = "SCO"
                        },
                        new
                        {
                            Id = 4,
                            Name = "England",
                            ShortName = "ENG"
                        });
                });

            modelBuilder.Entity("MockAPI.Data.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Chelmsford, Essex",
                            CountryId = 4,
                            Description = "From the outside this house looks gorgeous. It has been built with wheat colored bricks and has sandstone decorations. Small, octagon windows let in plenty of light and have been added to the house in a very asymmetric way.",
                            Name = "3 Bedroom Detached House",
                            Postcode = "CM2 1AA",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "London Road, Cardiff",
                            CountryId = 2,
                            Description = "The house is equipped with an average kitchen and one large bathroom, it also has a comfortable living room, two bedrooms, a large dining room, a bar and a snug basement.",
                            Name = "3 Bedroom State House",
                            Postcode = "CA2 9KK",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            Address = "Old Town, Edinburgh",
                            CountryId = 3,
                            Description = "The roof is high and v-shaped and is covered with wood shingles. One large chimney sits at the side of the house. A few round, small windows let in enough light to the rooms below the roof.\nThe house itself is surrounded by paved ground, with various party spots, like a fancy barbeque and a firepit.\n",
                            Name = "2 Bedroom City Flat",
                            Postcode = "ED3 2HQ",
                            Rating = 4.9000000000000004
                        });
                });

            modelBuilder.Entity("MockAPI.Data.House", b =>
                {
                    b.HasOne("MockAPI.Data.Country", "Country")
                        .WithMany("Houses")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MockAPI.Data.Country", b =>
                {
                    b.Navigation("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
